<div class="content">
        	<?php
			 if(isset($_GET['quanly'])){
				$tam=$_GET['quanly'];
			}else{
				$tam='';
			}if($tam=='quanlyloaisanpham'){
				include('modules/quanlyloaisanpham/main.php');
			}if($tam=='quanlysanpham'){
				include('modules/quanlysanpham/main.php');
			}if($tam=='quanlysize'){
				include('modules/quanlysize/main.php');
			}if($tam=='banh'){
				include('modules/banh/main.php');
			}
			if($tam=='quanlysale'){
				include('modules/quanlysale/main.php');
			}if($tam=='quanlydonhang'){
				include('modules/quanlydonhang/main.php');
			}
			?>	
        </div>